### ISSUE TITLE
[Question] Apply shape to MaterialCardView

### ISSUE THREAD

**Issue by GuilhE** [StylingAndroid/MaterialShape#1]
I’m trying to apply this shape to a MaterialCardView::

```
binding.card.background = MaterialShapeDrawable(
    ShapeAppearanceModel.builder()
        .setAllCornerSizes(5.dpToPx().toFloat())
        .setTopEdge(object : TriangleEdgeTreatment(10.dpToPx().toFloat(), false){
            override fun getEdgePath(length: Float, center: Float, interpolation: Float, shapePath: ShapePath) {
                super.getEdgePath(length, 12.dpToPx().toFloat(), interpolation, shapePath)
            }
        })
        .build()
).apply {
    fillColor = resourcesProvider().colorStateListFromAttr(R.attr.colorSurface, R.style.App_CardView)
}
```

Problem is, it only works if I apply to a MaterialCardView child… Which would work if I didn’t use elevation because if I do I’ll get a funky result in the “topEdge”:

```
<com.google.android.material.card.MaterialCardView
    style="@style/Widget.MaterialComponents.CardView"
    android:layout_width="match_parent"
    android:layout_height="wrap_content"
    android:layout_marginStart="20dp"
    android:layout_marginTop="5dp"
    android:layout_marginEnd="20dp"
    android:clipChildren="false"
    app:cardElevation="10dp">

    <androidx.constraintlayout.widget.ConstraintLayout
        android:layout_width="match_parent"
        android:layout_height="100dp"
        android:layout_marginTop="10dp"> //without this margin wont work
```

![Screenshot 2020-05-25 at 17 55 37](https://user-images.githubusercontent.com/2677139/82831862-78203c80-9eb1-11ea-8821-b82d91bdf04a.png)

What am i missing?

ps: 
https://github.com/StylingAndroid/MaterialShape/blob/ac5f115445d7a756d86074770c63297d1bad457f/app/src/main/java/com/stylingandroid/materialshape/MainActivity.kt#L44

You may find [this](https://github.com/GuilhE/ResourcesProvider-ktx) helpful :)

**Comment by StylingAndroid** [comment]
This is not an issue with the code in this repo and our is inappropriate to use GitHub issues in this way.
